### ISSUE TITLE
AttributeError: 'numpy.bytes_' object has no attribute 'delta

### ISSUE THREAD

**Issue by moghadas76** [VincLee8188/GMAN-PyTorch#12]
AttributeError: 'numpy.bytes_' object has no attribute 'delta'. Did you mean: 'data'?

loading data...
Traceback (most recent call last):
  File "/kaggle/working/GMAN-PyTorch/main.py", line 60, in <module>
    testY, SE, mean, std) = load_data(args)
  File "/kaggle/working/GMAN-PyTorch/utils/utils_.py", line 78, in load_data
    // time.freq.delta.total_seconds()

**Comment by serenaand** [comment]
change the code in utils_.py ,the def load_data(args): function
 change ”timeofday = (time.hour * 3600 + time.minute * 60 + time.second) \
            // time.freq.delta.total_seconds()”   
to ‘’timeofday = (time.hour * 3600 + time.minute * 60 + time.second) // args.time_slot
    timeofday = torch.reshape(torch.tensor(timeofday), (-1, 1))‘’

**Comment by zhifine** [comment]
Is "timeofday = (time.hour * 3600 + time.minute * 60 + time.second) // 60//args.time_slot" better?
